name: Rust - Buildpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Install Pack CLI
      uses: buildpacks/github-actions/setup-pack@v5.0.0
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image using Buildpacks
      run: |
        pack build ${{ secrets.DOCKER_USERNAME }}/rust-rocket-buildpacks --buildpack docker.io/paketocommunity/rust --builder paketobuildpacks/builder-jammy-full --path . --env "PROCFILE=web: ROCKET_PORT=8888 ./target/release/hello_rocket"
        docker push ${{ secrets.DOCKER_USERNAME }}/rust-rocket-buildpacks:latest
