name: Rust - Buildpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the image using the Rust buildpack
      uses: buildpacks/github-actions/setup-pack@v5.0.0
      run: pack build ${{ secrets.DOCKER_USERNAME }}/rust-rocket-buildpacks --buildpack docker.io/paketocommunity/rust --builder paketobuildpacks/builder-jammy-full --path .
    
    - name: Log in to Docker Hub and Push the image
      uses: docker/login-action@v2
      with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
      run: docker push ${{ secrets.DOCKER_USERNAME }}/rust-rocket-buildpacks:latest
